//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjFriendbookWebServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interested
    {
        public int RefInterested { get; set; }
        public string InterestedType { get; set; }
    }
}
