//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjFriendbookWebServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int RefMessage { get; set; }
        public string Message1 { get; set; }
        public Nullable<int> RefSender { get; set; }
        public Nullable<int> RefReceiver { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsNew { get; set; }
    }
}
