//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjFriendbookWebServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FriendbookSQLEntities : DbContext
    {
        public FriendbookSQLEntities()
            : base("name=FriendbookSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyType> BodyTypes { get; set; }
        public virtual DbSet<DrinkingType> DrinkingTypes { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Ethinicity> Ethinicities { get; set; }
        public virtual DbSet<Interested> Interesteds { get; set; }
        public virtual DbSet<LookingFor> LookingFors { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<SmokingType> SmokingTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
    }
}
