//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjFriendbookWebServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int RefUser { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string psw { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string postalcode { get; set; }
        public string ImageUrl { get; set; }
        public string height { get; set; }
        public Nullable<int> RefBodyType { get; set; }
        public Nullable<int> RefEthinicity { get; set; }
        public Nullable<int> RefReligion { get; set; }
        public Nullable<int> RefInterested { get; set; }
        public Nullable<int> RefLookingFor { get; set; }
        public Nullable<int> RefEducation { get; set; }
        public Nullable<int> RefSmoking { get; set; }
        public Nullable<int> RefDrinking { get; set; }
    }
}
